//Testing in 129 for Jenkins jon Android_Test
pipeline 
{
    agent none
    stages 
    {
        stage('SCM Poll') 
        {
            agent any
            steps 
            {  	
				sh '''ls -la'''
				sh '''pwd'''
				sh '''ssh \'318356@10.10.196.129\' docker volume create volAndroidTest'''
				
               echo "********Waiting for SCM event - IN PROGRESS***********"
                /*
				script 
				{
				    properties([pipelineTriggers([pollSCM('* * * * *')])])
				}
				echo "Waiting for SCM event - Done"
				git branch: 'master', credentialsId: 'nandu', url: 'https://github.com/nandunarayanan/Android_Demo.git'
				*/
				
				/*
				
				checkout([$class: 'GitSCM', 
				branches: [[name: "origin/master"]], 
				userRemoteConfigs: [[
                url: 'https://github.com/nandunarayanan/Android_Demo.git']]
				])
				*/
				echo "Testing for SCM event - Done"
				echo "************copying the git update to the volume- IN PROGRESS***********"
				sh '''ssh \'318356@10.10.196.129\' /home/318356/copy.sh'''
				echo  "************copying the git update to the volume - DONE ****************"
				sh '''ls -la'''
				sh '''pwd'''
				
            }
        }
        
        stage('BuildManager')
        {   
            agent any
            steps
            {
                sh '''ssh \'318356@10.10.196.129\' docker pull localhost:5000/android_test_build:v2'''
                sh '''ssh \'318356@10.10.196.129\' docker run --name Build -v volAndroidTest:/src localhost:5000/android_test_build:v2'''
            }
        }
        
        
        
        stage('TestRunner')
        {   
            agent any
            steps
            {
                 echo "********Test Runner***********"
               sh '''ssh \'318356@10.10.196.129\' docker pull localhost:5000/android_test_run:v1'''
             // sh '''ssh \'318356@10.10.196.129\' docker run --name Runner -v volAndroidTest:/src localhost:5000/android_test_run:v1'''
            }
        }
        /*
        stage('Publishing Result')
        {
            agent any
            steps
            {
                sh '''ssh \'318356@10.10.196.129\' /home/318356/copy_xml.sh'''
                step([$class: 'Publisher'])
            }
            
        }
        */
        
        stage('Removal of build and volumes')
        {   
            agent any
            steps
            {
                sh '''ssh \'318356@10.10.196.129\' docker stop Build'''
                sh '''ssh \'318356@10.10.196.129\' docker rm Build'''
              //  sh '''ssh \'318356@10.10.196.129\' docker stop Runner'''
               // sh '''ssh \'318356@10.10.196.129\' docker rm Runner'''
				sh '''ssh \'318356@10.10.196.129\' docker volume rm -f volAndroidTest'''
            }
        }
    }
}
